### ISSUE TITLE
Doesn't work with jQuery 3.2.1 and above

### ISSUE THREAD

**Issue by nchankov** [javiertoledo/bootstrap-rating-input#64]
Basically it give an error like:
i.prevAll(...).andSelf is not a function

How to reproduce it: change the jquery url from 1.10.2 ro 3.2.1 and you should see it.

**Comment by nchankov** [comment]
Sorry, my fault, it's fixed on that repository, but it's still with andSelf() in the npm repo

**Comment by javiertoledo** [comment]
No problem, versioning is hard! :-)
